name: Question
description: File a question
title: "[Question]: "
labels: ["question"]
assignees:
  - feduke-nukem
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this question!
  - type: textarea
    id: your-question
    attributes:
      label: What is your question?
      description: Ask a question.
      placeholder: Your question
      value: "Your question!"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/feduke-nukem/flutter_easy_dialogs/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
