name: full_screen_dialog_manager
description: Full screen dialog manager for using via `flutter_easy_dialogs` package.
version: 1.0.3+2
homepage: https://github.com/feduke-nukem/flutter_easy_dialogs
repository: https://github.com/feduke-nukem/flutter_easy_dialogs/tree/master/packages/full_screen_dialog_manager

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_easy_dialogs: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  
  golden_toolkit: ^0.15.0
  dart_code_metrics: ^5.6.0 

flutter:
 
