name: flutter_easy_dialogs
description: Easy, lightweight and flexible service for showing dialogs inside your Flutter application.
version: 2.0.5
homepage: https://github.com/feduke-nukem/flutter_easy_dialogs
repository: https://github.com/feduke-nukem/flutter_easy_dialogs/tree/master/flutter_easy_dialogs

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  back_button_interceptor: ^6.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  
  dart_code_metrics: ^5.6.0 

