name: example
description: Positioned Dialog Manager examples.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
 
dependencies:
  flutter:
    sdk: flutter

  flutter_easy_dialogs: any
  examples: 
    path: ../../../examples/
  positioned_dialog_manager: any

dependency_overrides:
  flutter_easy_dialogs:
    path: ../../flutter_easy_dialogs
  positioned_dialog_manager:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
