name: full_screen_dialog_manager

on:
  push:
    paths:
      - "packages/full_screen_dialog_manager/**"
      - ".github/workflows/full_screen_dialog_manager.yaml"

  pull_request:
    paths:
      - "packages/full_screen_dialog_manager/**"
      - ".github/workflows/full_screen_dialog_manager.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/full_screen_dialog_manager

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: packages/full_screen_dialog_manager/coverage/lcov.info
          min_coverage: 72

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  pana:
    defaults:
      run:
        working-directory: packages/full_screen_dialog_manager

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0

      - name: Install Dependencies
        run: |
          flutter packages get
          flutter pub global activate pana
          sudo apt-get install webp
      - name: Verify Pub Score
        run: ../../tool/verify_pub_score.sh